### ISSUE TITLE
More portable code

### ISSUE THREAD

**Issue by tryingsomestuff** [konsolas/ToppleChess#14]
Hi Vincent. I compile Topple yesterday using g++. I guess you are using c++17 just for clamp function. C++14 is enough without clamp that can be easily replaced. Also I guess you use CLANG because some headers are missing (clang add them automatically sometimes). I think you can made Topple more portable easily. I have a patch if you want.
[vivien.patch.txt](https://github.com/konsolas/ToppleChess/files/2848781/vivien.patch.txt)

**Comment by konsolas** [comment]
Many thanks for your help;

I do plan to use some C++17 features, such as std::optional, and I'd like to stay up to date with the language, so I intend to avoid moving to C++14, but your suggestions are greatly appreciated.

**Comment by konsolas** [comment]
I've fixed the header issues in 0.6.0.

Thanks :)

**Comment by tryingsomestuff** [comment]
great ! I'll test that soon
    Le mercredi 15 mai 2019 à 23:38:42 UTC+2, Vincent <notifications@github.com> a écrit :  
 
 
I've fixed the header issues in 0.6.0.

Thanks :)
