### ISSUE TITLE
compile unix

### ISSUE THREAD

**Issue by tschmoderer** [konsolas/ToppleChess#19]
ty konsolas for your engine! 
can you provide a makefile for unix compilation please ?

**Comment by konsolas** [comment]
Hi,

As far as I know, Topple currently won't run on linux due some strange behaviour with pthreads.

You can get it to compile by adding `target_link_libraries(Topple pthread)` to the bottom of CMakeLists.txt, before building as usual with `cmake . && make Topple`

I haven't been able to resolve the segfault yet so I'm not sure when Topple will actually be able to run on linux.

**Comment by konsolas** [comment]
@tschmoderer 0.6.0 should compile on linux with cmake now.
