### ISSUE TITLE
new compile for coffee lake micro-architecture?

### ISSUE THREAD

**Issue by yellow-panther** [konsolas/ToppleChess#23]
Hello  konsolas,
https://en.wikipedia.org/wiki/Coffee_Lake - do you have plans for upcoming Topple versions to host it on GitHub?

Regards,

**Comment by konsolas** [comment]
Hi,

Coffee Lake is functionally identical to the Skylake core. As such, GCC doesn't provide a `-march` setting for it. You should use the Skylake compile for intel 6th, 7th, 8th and 9th gen CPUs.
