### ISSUE TITLE
ToppleChess not compiling on MacOS: Issue with evaluator_t

### ISSUE THREAD

**Issue by mphuget** [konsolas/ToppleChess#25]
Hello, 

Just to let you know, I tried to compile ToppleChess on MacOS (10.14.5) with CMake (3.15.rc1) and I got two errors: 

/Users/marc-philippehuget/Chess/ToppleChess/tuning/tuner.cpp:71:17: error: no
      matching constructor for initialization of 'evaluator_t'
    evaluator_t evaluator(current_params, 4096);
                ^         ~~~~~~~~~~~~~~~~~~~~
/Users/marc-philippehuget/Chess/ToppleChess/tuning/../eval.h:208:5: note: 
      candidate constructor not viable: no known conversion from 'eval_params_t'
      to 'const processed_params_t' for 1st argument
    evaluator_t(const processed_params_t &params, size_t pawn_hash_size);
    ^
/Users/marc-philippehuget/Chess/ToppleChess/tuning/../eval.h:200:7: note: 
      candidate constructor (the implicit copy constructor) not viable: requires
      1 argument, but 2 were provided
class evaluator_t {
      ^
/Users/marc-philippehuget/Chess/ToppleChess/tuning/../eval.h:200:7: note: 
      candidate constructor (the implicit move constructor) not viable: requires
      1 argument, but 2 were provided
/Users/marc-philippehuget/Chess/ToppleChess/tuning/tuner.cpp:77:25: error: no
      matching constructor for initialization of 'evaluator_t'
            evaluator_t local_evaluator(current_params, 8 * MB);
                        ^               ~~~~~~~~~~~~~~~~~~~~~~
/Users/marc-philippehuget/Chess/ToppleChess/tuning/../eval.h:208:5: note: 
      candidate constructor not viable: no known conversion from 'eval_params_t'
      to 'const processed_params_t' for 1st argument
    evaluator_t(const processed_params_t &params, size_t pawn_hash_size);
    ^
/Users/marc-philippehuget/Chess/ToppleChess/tuning/../eval.h:200:7: note: 
      candidate constructor (the implicit copy constructor) not viable: requires
      1 argument, but 2 were provided
class evaluator_t {
      ^
/Users/marc-philippehuget/Chess/ToppleChess/tuning/../eval.h:200:7: note: 
      candidate constructor (the implicit move constructor) not viable: requires
      1 argument, but 2 were provided
2 errors generated.

I will check later and try to find a fix

Regards, 
mph

**Comment by konsolas** [comment]
You seem to be trying to build the ToppleTune target - that one won't compile yet because I haven't updated the tuner for the new evaluation function.

Instead, please just `make Topple` to only build the engine.

**Comment by mphuget** [comment]
Dear Vincent, 

OK, got it! Just to clarify if some others have trouble when compiling on MacOS:
1. In ToppleChess dir, do cmake -S . -B build
2. cd to build
3. make Topple

In the directory, there is a Topple executable. 
Make sure to use cmake with a version > 3.8
