### ISSUE TITLE
new Windows x64 compile

### ISSUE THREAD

**Issue by yellow-panther** [konsolas/ToppleChess#3]
Hello Vincent,

cf. http://talkchess.com/forum3/viewtopic.php?f=2&t=67634 - engine has still problems with rules infraction and time forfeit Arena GUI www.playwitharena.com Windows 7 SP1 64 bit
[games pgn + arena debug.zip](https://github.com/konsolas/ToppleChess/files/2068842/games.pgn.arena.debug.zip)

**Comment by konsolas** [comment]
Hi; thanks for testing.

 I recently created a new commit with several fixes for search issues. Were you using this one?

If you need a windows build, a mingw-w64 compile can be found at https://transfer.sh/tHCr7/Topple.exe

**Comment by yellow-panther** [comment]
Hello,

it would be a good idea to contact "pferd" = German for knight or horse on
the CCC talkchess-forum directly. His latest compile is from 2018-06-03.
I cannot use your mingw64-compile, it crashes immediately after a
double-click on the .exe-file- on my ivy-bridge quad core i5 (it supports
AVX and POPCNT, but not bmi2)
https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets

2018-06-04 20:20 GMT+02:00 Vincent <notifications@github.com>:

**Comment by konsolas** [comment]
Looks like they've posted a new compile with the latest commit. I'll ask about the settings.
