### ISSUE TITLE
Fail compile on ARM Cortex-A53 SBC

### ISSUE THREAD

**Issue by rontant** [konsolas/ToppleChess#30]
When trying to compile on my Rock64 ARM Cortex-A53 SBC, I got the following errors:

> root@rock64:~/ToppleChess# cmake .
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Found Threads: TRUE
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /root/ToppleChess

> root@rock64:~/ToppleChess# make -j4
> Scanning dependencies of target Topple
> Scanning dependencies of target ToppleTest
> Scanning dependencies of target ToppleTexelTune
> Scanning dependencies of target ToppleTune
> [  1%] Building CXX object CMakeFiles/Topple.dir/board.cpp.o
> [  3%] Building CXX object CMakeFiles/ToppleTest.dir/board.cpp.o
> [  4%] Building CXX object CMakeFiles/ToppleTexelTune.dir/board.cpp.o
> [  6%] Building CXX object CMakeFiles/ToppleTune.dir/board.cpp.o
> [  7%] Building CXX object CMakeFiles/ToppleTune.dir/endgame.cpp.o
> [  9%] Building CXX object CMakeFiles/Topple.dir/endgame.cpp.o
> [ 10%] Building CXX object CMakeFiles/ToppleTexelTune.dir/endgame.cpp.o
> In file included from /root/ToppleChess/endgame.h:10:0,
>                  from /root/ToppleChess/endgame.cpp:5:
> /root/ToppleChess/board.h:85:10: error: ‘vector’ in namespace ‘std’ does not name a template type
>      std::vector<game_record_t> record;
>           ^~~~~~
> /root/ToppleChess/board.h: In function ‘std::ostream& operator<<(std::ostream&, const board_t&)’:
> /root/ToppleChess/board.h:97:32: error: ‘const struct board_t’ has no member named ‘record’
>      for (int i = 1; i <= board.record.size(); i++) {
>                                 ^~~~~~
> /root/ToppleChess/board.h:102:25: error: ‘const struct board_t’ has no member named ‘record’
>          stream << board.record[i].prev_move << " ";
>                          ^~~~~~
> In file included from /root/ToppleChess/endgame.h:10:0,
>                  from /root/ToppleChess/endgame.cpp:5:
> /root/ToppleChess/board.h:85:10: error: ‘vector’ in namespace ‘std’ does not name a template type
>      std::vector<game_record_t> record;
>           ^~~~~~
> /root/ToppleChess/board.h: In function ‘std::ostream& operator<<(std::ostream&, const board_t&)’:
> /root/ToppleChess/board.h:97:32: error: ‘const struct board_t’ has no member named ‘record’
>      for (int i = 1; i <= board.record.size(); i++) {
>                                 ^~~~~~
> /root/ToppleChess/board.h:102:25: error: ‘const struct board_t’ has no member named ‘record’
>          stream << board.record[i].prev_move << " ";
>                          ^~~~~~
> In file included from /root/ToppleChess/endgame.h:10:0,
>                  from /root/ToppleChess/endgame.cpp:5:
> /root/ToppleChess/board.h:85:10: error: ‘vector’ in namespace ‘std’ does not name a template type
>      std::vector<game_record_t> record;
>           ^~~~~~
> /root/ToppleChess/board.h: In function ‘std::ostream& operator<<(std::ostream&, const board_t&)’:
> /root/ToppleChess/board.h:97:32: error: ‘const struct board_t’ has no member named ‘record’
>      for (int i = 1; i <= board.record.size(); i++) {
>                                 ^~~~~~
> /root/ToppleChess/board.h:102:25: error: ‘const struct board_t’ has no member named ‘record’
>          stream << board.record[i].prev_move << " ";
>                          ^~~~~~
> CMakeFiles/Topple.dir/build.make:86: recipe for target 'CMakeFiles/Topple.dir/endgame.cpp.o' failed
> make[2]: *** [CMakeFiles/Topple.dir/endgame.cpp.o] Error 1
> CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/Topple.dir/all' failed
> make[1]: *** [CMakeFiles/Topple.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 12%] Building CXX object CMakeFiles/ToppleTexelTune.dir/bb.cpp.o
> CMakeFiles/ToppleTexelTune.dir/build.make:86: recipe for target 'CMakeFiles/ToppleTexelTune.dir/endgame.cpp.o' failed
> make[2]: *** [CMakeFiles/ToppleTexelTune.dir/endgame.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> [ 13%] Building CXX object CMakeFiles/ToppleTest.dir/endgame.cpp.o
> CMakeFiles/ToppleTune.dir/build.make:86: recipe for target 'CMakeFiles/ToppleTune.dir/endgame.cpp.o' failed
> make[2]: *** [CMakeFiles/ToppleTune.dir/endgame.cpp.o] Error 1
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/ToppleTune.dir/all' failed
> make[1]: *** [CMakeFiles/ToppleTune.dir/all] Error 2
> [ 15%] Building CXX object CMakeFiles/ToppleTest.dir/bb.cpp.o
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ToppleTexelTune.dir/all' failed
> make[1]: *** [CMakeFiles/ToppleTexelTune.dir/all] Error 2
> [ 16%] Building CXX object CMakeFiles/ToppleTest.dir/hash.cpp.o
> In file included from /root/ToppleChess/endgame.h:10:0,
>                  from /root/ToppleChess/endgame.cpp:5:
> /root/ToppleChess/board.h:85:10: error: ‘vector’ in namespace ‘std’ does not name a template type
>      std::vector<game_record_t> record;
>           ^~~~~~
> /root/ToppleChess/board.h: In function ‘std::ostream& operator<<(std::ostream&, const board_t&)’:
> /root/ToppleChess/board.h:97:32: error: ‘const struct board_t’ has no member named ‘record’
>      for (int i = 1; i <= board.record.size(); i++) {
>                                 ^~~~~~
> /root/ToppleChess/board.h:102:25: error: ‘const struct board_t’ has no member named ‘record’
>          stream << board.record[i].prev_move << " ";
>                          ^~~~~~
> CMakeFiles/ToppleTest.dir/build.make:86: recipe for target 'CMakeFiles/ToppleTest.dir/endgame.cpp.o' failed
> make[2]: *** [CMakeFiles/ToppleTest.dir/endgame.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/ToppleTest.dir/all' failed
> make[1]: *** [CMakeFiles/ToppleTest.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

Would you like to give some pointers? Thanks in advance.

**Comment by konsolas** [comment]
Should be fixed now - enabled github actions.
