### ISSUE TITLE
rule infractions by pferd´s compile from 2018-06-05

### ISSUE THREAD

**Issue by yellow-panther** [konsolas/ToppleChess#4]
Hello Vincent,

cf. 
[Topple Chess gauntlet.zip](https://github.com/konsolas/ToppleChess/files/2076438/Topple.Chess.gauntlet.zip)

round 2 vs. JaksaH
round 6 vs. Pidgeon, Sayuri
round 7 vs. Hoichess, Sayuri
round 8 vs. Pidgeon
round 9 vs. Hoichess, Pidgeon

no time forfeits by Topple Chess, twice by Deepov

Regards,

**Comment by konsolas** [comment]
The a1b1 bug should be sorted by 760b673f54bc8e14501bae0cd88eddc679c8f86c

You can download the latest build (windows/ivybridge, no BMI2) at https://transfer.sh/cfqH6/Topple.exe

Best wishes
