### ISSUE TITLE
Topple Chess x64 for Windows

### ISSUE THREAD

**Issue by yellow-panther** [konsolas/ToppleChess#5]
[gauntlet ChessGUI.zip](https://github.com/konsolas/ToppleChess/files/2081269/gauntlet.ChessGUI.zip)
[gauntlet Arena.zip](https://github.com/konsolas/ToppleChess/files/2081276/gauntlet.Arena.zip)
![topple chess 1](https://user-images.githubusercontent.com/17721887/41113580-570a1f94-6a82-11e8-8fbe-91b22f2d9132.jpg)
![topple chess 2](https://user-images.githubusercontent.com/17721887/41113585-5ad726b2-6a82-11e8-9595-93fb792548ae.jpg)
![topple chess 3](https://user-images.githubusercontent.com/17721887/41113589-5f11aa86-6a82-11e8-9d48-f59eac8d32f3.jpg)
![topple chess 4](https://user-images.githubusercontent.com/17721887/41113593-62c20176-6a82-11e8-9635-0c1b77a0d8d1.jpg)
![topple chess 5](https://user-images.githubusercontent.com/17721887/41113604-6aac14f8-6a82-11e8-8cb8-d95b0ea4c7dd.jpg)
![topple chess 6](https://user-images.githubusercontent.com/17721887/41113606-6d7e48f4-6a82-11e8-8a69-a5a4bf3755ca.jpg)

Hello Vincent,

cf. attachments - I used these editions: http://www.chess2u.com/t11859-topplechess and https://transfer.sh/cfqH6/Topple.exe 

To use the logos with a an interface like Arena, ChessGUI or WinBoard > rename .jpeg into .bmp (bitmap) e.g. http://www.photofiltre.com/

Both have still bugs....

Regards,

**Comment by konsolas** [comment]
Looks like the bug here is from Topple detecting a position repetition in the move history, and refusing to search because it thinks the game should be over: this is because it treats a position as a draw when it has only been repeated twice, as opposed to three times.

**Comment by konsolas** [comment]
win/ivybridge/O3 build of the latest commit can be found at https://transfer.sh/hMqBd/Topple.exe

Thanks for testing :)
