### ISSUE TITLE
problem with three-fold-repetition seems to be solved

### ISSUE THREAD

**Issue by yellow-panther** [konsolas/ToppleChess#6]
Hello Vincent,
https://transfer.sh/hMqBd/Topple.exe runs now on Arena GUI without former problems, but Joost´s compile https://www.dropbox.com/s/s2lsvorw7u1hi34/ToppleChess.rar?dl=0 has some bugs with time forfeit and illegal moves. Arena + ChessGUI debug files are attached. Windows 7 64 bit SP1 = OS

It would be a good idea to host separately the latest win64 build + source code on a sub-directory ToppleChess/releases with a rev number.....
[Topple Chess JB.zip](https://github.com/konsolas/ToppleChess/files/2083795/Topple.Chess.JB.zip)
[Topple Chess VT.zip](https://github.com/konsolas/ToppleChess/files/2083798/Topple.Chess.VT.zip)

Regards,

**Comment by konsolas** [comment]
I think that Joost's compile doesn't have the latest commit, so I'd assume that's the cause of the problems.

I plan to set up some sort of continuous integration in the future to allow for releases on GitHub.

**Comment by konsolas** [comment]
I've started adding some version numbers. When I have a full implementation of the UCI protocol, I'll start using GitHub releases.

In the meantime, a build of v0.0.1 can be found here: https://transfer.sh/NINcH/Topple.exe

**Comment by konsolas** [comment]
Builds are now being hosted on the releases tab.
